# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b444845de5211854a3c079d1ffee37bb922d967081f3f64a5cdf7e532ad542d7c66098eb1a555e9593ba0e4a1292aa3927a3e827bd67a2520a3c3cab6215dd

test:
  secret_key_base: 7a2bda77bc79b459191d1796969812da6196a66c58b69800116b8a222e192e0b45935af24b5c3de4c8c5086b21cc4b614a3137f1b37cb384684234a9ce2b8652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
